### ISSUE TITLE
Add pictures

### ISSUE THREAD

**Issue by faebser** [faebser/10201#12]
![img_3457](https://cloud.githubusercontent.com/assets/333862/23943242/195fdcda-096f-11e7-94db-9a6d40dfc3e8.JPG)
![iooi2_2](https://cloud.githubusercontent.com/assets/333862/23943241/19576f0a-096f-11e7-8b83-dfaf0faa70c9.jpg)

I got an email from caro/alex with the request to add these pictures to the site. Can you do that?

**Comment by Giublilanda** [comment]
Yes!

**Comment by faebser** [comment]
How to do it:

* make sure all the necessary stuff is running (see the readme)
* download the files and copy them into ```assets/images```
* the file that you need to change is located at ```site/snippets/project.php```
* use the img tag that is already there to add the new images
* check your local version if it works
* use the github software to commit and sync your changes
* please add the issue number with an # in front in the commit comment so we will see it here

**Comment by Giublilanda** [comment]
Add more space on the bottom
