### ISSUE TITLE
The project

### ISSUE THREAD

**Issue by Giublilanda** [faebser/10201#3]
Numbers on the left:
- make the yellow over just on the numbers not on the white
- make the numbers BOLD
- font-size: number 56 - subtitle 20

**Comment by Giublilanda** [comment]
All the titles should be: 
- bold
- font-size: 26

**Comment by Giublilanda** [comment]
First text block (Exploring the definition of what a museum’s roles are within the public sphere, the MuDA wants to develop a project embracing and bridging communities, starting with the zeros and ones in our own physical neighborhood of Kreis 5.) 
- bold

**Comment by Giublilanda** [comment]
From "Kicking ..." to "... basis"  
- font-size 16 px
- book
- 28pt of distance between the lines

Before the block "gritty.." add the title **Kreis 5**

**Comment by Giublilanda** [comment]
1. Move the block "Beyond the statistic... daily basis?" on the left beyond the numbers.
We need to give more movement in the page.

2. After this we can add the image Alexa senti to us (the one with the googlemap view)

3. Last block "The MuDA will become..." lets make it bigger and:
- centered in the page
- bold
- font-size 24

**Comment by faebser** [comment]
let's do this tomorrow together
