### ISSUE TITLE
The organization

### ISSUE THREAD

**Issue by Giublilanda** [faebser/10201#6]
- Title: The organization
- On the left: before logo then img
- More space between the elements

- font-size texts: 19 - book
- Cta hover: like here http://muda.co/lab212/

**Comment by faebser** [comment]
- [x] Title: The organization
- [x] On the left: before logo then img
- [ ] More space between the elements
- [ ] font-size texts: 19 - book
- [x] Cta hover: like here http://muda.co/lab212/

**Comment by faebser** [comment]
About the fonts, I think we should work on them together tomorrow

**Comment by Giublilanda** [comment]
I think we need to make the images much more smaller..
